export const areas = ['MCP', 'MCPe', 'MCVP oGV', 'MCVP oGT', 'MCVP iGT',  'MCVP Marketing','LCP', 'LCVP oGV', 'LCVP oGT', 'LCVP iGV',  'LCVP iGT',  'LCVP Marketing']
export const entities = [
    "ARMENIA", "AUSTRIA", "AZERBAIJAN", "BELGIUM", "BOSNIA AND HERZEGOVINA",
    "BULGARIA", "CROATIA", "CZECH REPUBLIC", "DENMARK", "EGYPT", "ESTONIA",
    "FRANCE", "GEORGIA", "GERMANY", "GREECE", "HUNGARY", "ITALY", "KAZAKHSTAN",
    "KYRGYZSTAN", "MAINLAND OF CHINA", "MOLDOVA", "NEW ZEALAND", "POLAND",
    "PORTUGAL", "ROMANIA", "RUSSIA", "SERBIA", "SLOVAKIA", "SPAIN", "SWITZERLAND",
    "THE NETHERLANDS", "TUNISIA", "TURKIYE", "UKRAINE", "UNITED KINGDOM"
];
